project:
  type: book

book:
  title: "InSAR 笔记"
  author: "Kang Liang"
  logo: cover.png

  chapters:
    - index.qmd
    - preface.qmd
    - part: SAR/index.qmd
      chapters: 
        - SAR/imaging_system.qmd
        - ./SAR/geometry.qmd
        - ./SAR/SAR_pulse_response.ipynb
    - part: InSAR/index.qmd
      chapters:
        - InSAR/geocoding.qmd
    - references.qmd

  sidebar:
    border: true
  repo-url: https://github.com/kanglcn/insar101
  repo-actions: [edit, issue]
  page-footer:
    border: true
    center: "Copyright 2022, Kang Liang. All right reserved."

bibliography: references.bib

format:
  html:
    code-fold: true
    theme: cosmo
    fontsize: 1rem

execute:
  freeze: auto



