project:
  type: book

book:
  title: "InSAR 笔记"
  author: "Kang Liang"

  chapters:
    - index.qmd
    - preface.qmd
    - part: basic/index.qmd
      chapters: 
              - basic/time.qmd
    - part: SAR/index.qmd
      chapters: 
        - SAR/imaging_system.qmd
        - ./SAR/geometry.qmd
        - ./SAR/SAR_pulse_response.ipynb
    - part: InSAR/index.qmd
      chapters:
        - InSAR/geocoding.qmd
    - text: "---"
    - references.qmd

  sidebar:
    border: true
    logo: cover.png

  site-url: https://insarkl.com/insar101
  repo-url: https://github.com/kanglcn/insar101
  repo-actions: [edit, issue, source]
  page-footer:
    border: true
    center: "Copyright 2022, Kang Liang. All rights reserved."
    background: light

  comments:
    giscus:
      repo: kanglcn/insar101

bibliography: references.bib
reference-location: margin
citation-location: margin

format:
  html:
    theme:
      light: [default, custom.scss]
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Roboto"
    smooth-scroll: true
    toc-depth: 4
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true

execute:
  freeze: auto



